<?php

namespace Tests\Feature;

use App\User;
use Faker\Factory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserLoginTest extends TestCase
{
    protected $faker;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
    }

    use RefreshDatabase;
    /** @test **/
    public function test_user_can_view_a_login_form()
    {
        $response = $this->get('/login');
        $response->assertSuccessful();
        $response->assertViewIs('auth.login');
    }
    /** @test **/
    public function correct_response_after_user_successfully_logins()
    {
        $user = factory(User::class)->create();

        $this->post(route('login'),[
            'email' => $user->email,
            'password' => 'password'
        ])->assertRedirect(route('home'));
    }
    /** @test **/
    public function user_cannot_login_with_incorrect_password()
    {
        $user = factory(User::class)->create();

        $response = $this->post(route('login'),[
            'email' => $user->email,
            'password' => 'wrong-password'
        ]);

        $response->assertSessionHasErrors('email');
        $this->assertTrue(session()->hasOldInput('email'));
        $this->assertFalse(session()->hasOldInput('password'));
        $this->assertFalse(session()->hasOldInput('phone'));
        $this->assertFalse(session()->hasOldInput('location'));
        $this->assertGuest();
    }
}
