<?php

namespace Tests\Unit;

use App\JobRequest;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class JobRequestTest extends TestCase
{
    use RefreshDatabase;

    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

    /** @test **/
    public function tutor_accept_job_request()
    {
        $this->authenticateTutor();
        $job_reqest = factory(JobRequest::class)->create();
        $job_reqest->assignReference();
        $this->assertNotEmpty($job_reqest->job_reference);
        $this->assertDatabaseCount('job_requests', 1);
        $job_reqest->assignATutor(auth()->user());
        $this->assertCount(1,auth()->user()->unreadNotifications);
        $job_reqest->changeJobStatus(3);
        $job = JobRequest::find(1);
        $this->assertEquals('Accept', $job->status);
    }
    /** @test **/
    public function tutor_declines_job_request()
    {
        $this->authenticateTutor();
        $job_reqest = factory(JobRequest::class)->create();
        $job_reqest->assignReference();
        $this->assertNotEmpty($job_reqest->job_reference);
        $this->assertDatabaseCount('job_requests', 1);
        $job_reqest->assignATutor(auth()->user());
        $this->assertCount(1,auth()->user()->unreadNotifications);
        $job_reqest->changeJobStatus(4);
        $job = JobRequest::find(1);
        $this->assertEquals('Decline', $job->status);
    }
}
